project:
  type: website
  
website:
  title: "Girl Guiding Bunkfest Tearoom 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: staffing.qmd
        text: Staffing
      - href: recipes.qmd
        text: Baking
      - href: faq.qmd
        text: FAQs 
  repo-url: https://github.com/AnyaJade/girl-guiding-bunkfest
  repo-branch: main

execute: 
  eval: true
  echo: false
  warning: false

format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    number-sections: false



