project:
  type: website
  
website:
  title: "Girlguiding Mad Hatter's Tearoom at Bunkfest 2025"
  navbar:
    left:
      - href: staffing.qmd
        text: Staffing
      - href: recipes.qmd
        text: Baking
      - href: faq.qmd
        text: FAQs 
      - href: map.qmd
        text: Bunkfest map
      - href: contact.qmd
        text: Contact us
    foreground: "#FFFFFF"
  page-footer:
    background: "#161b4e"
    foreground: "#FFFFFF"
    center: 
      - text: "Contact us"
        href: contact.qmd
      - icon: github
        href: https://github.com/AnyaJade/girl-guiding-bunkfest
      - icon: facebook
        href: https://www.facebook.com/GirlguidingWallingford/

execute: 
  eval: true
  echo: false
  warning: false



