## Frequently Asked Questions

Below are some frequently asked questions. For any thing else please [contact us](contact.qmd).

### How can I help?

There are many ways you can help us during Bunkfest or in the run up to it - let us know what you would like to do. We are currently seeking volunteers to:

- Help us with [staffing](staffing.qmd):
  - Setting up our tearoom on Thursday 28th Aug.
  - Volunteering in the tearoom on Friday 29th to Sunday 31st Aug.
  - Taking our tearoom down on Sunday 28th Aug.
- [Bake us cakes](recipes.qmd).
- Making decorations or displays over the summer.
- Visiting our tearoom during Bunkfest. We'll be in the Bullcroft.
- Or any other way you can think of. 

### Why are we fundraising?

We are fundraising to pay for repairs to our Wallingford hut, to support our girls on their trip to Mexico in 2026 and to raise money for our District general funds. This will help girls across Wallingford, Cholsey and Long Wittenham access Girlguiding opportunities, including things like uniforms, camps, flags, equipment and making sure no one misses out due to costs.

The Bunkfest Tearoom will also improve our visibility in the community and promote Girlguiding, team-building and friendship across the units. Getting involved in these fundraising opportunities strengthens all of our groups and the girls themselves in the long-term.

### Why can't we bake other cakes?

We have decided to use set recipes so that we can be sure of what stock we have and what ingredients have been used. This will help us on the day to better manage our use of stock and to help people with allergies and dietary requirements to enjoy our cakes safely.