## Rota

Each unit has been assigned a two hour slot to run the tearoom. **Unit leaders** are asked to please update the [staffing sign-up sheet](https://docs.google.com/document/d/1x_cJhxgbXt4jCWR6OjGeRFeREk8HUgJX7Es6h36PofY/) with names of volunteers available for their session. If you are not a leader and are looking to sign up or to check what you've signed up for, please contact your unit leaders or [contact us](contact.qmd).

:::panel-tabset

### Friday 29th Aug

| Time slot | Unit |
|---|------|
| 2pm - 4pm | Bunkfest planning committee & Rangers |
| 4pm - 6pm | Bunkfest planning committee & Rangers |

### Saturday 30th Aug

| Time slot | Unit |
|---|------|
| 10am - 12pm | 1st Wallingford Rainbows |
| 12pm - 2pm | 2nd Wallingford Guides |
| 2pm - 4pm | 1st Wallingford Guides |
| 4pm - 6pm | Long Wittenham Rainbows and Brownies |

### Sunday 31st Aug

| Time slot | Unit 
|---|------|
| 10am - 12pm | Cholsey Brownies and Rainbows |
| 12pm - 2pm | Wallingford Rangers |
| 2pm - 4pm | 2nd Wallingford Rainbows and 2nd Wallingford Brownies |
| 4pm - 6pm | 4th Wallingford Brownies and Cholsey Guides |

:::

## Roles

Each unit should recruit volunteers to fill the below roles. Volunteers can be leaders, young leaders, the girls, their families or anyone else willing to support us.

- Leader in charge / first aid.
- Order taker / money handler. Needs to be comfortable using the SumUp machine.
- Hot drinks maker.
- Cake server.
- Washing up.
- Front of house. This includes clearing and cleaning tables and welcoming customers.

Anyone who is aged 10 years or under can only be front of house or on washing up and should be supervised by another adult.

A member of the Girl Guiding Bunkfest tearoom committee will be on hand to help with setup (10am) and close down (6pm) each day.

### Volunteers for setting up and taking down

We are also looking for volunteers to help up set up the tearoom on Thursday 28th (time TBC) and to take it down on Sunday 31st (6-7pm). If you are available, please let us know.

## What to wear

We recommend wearing comfortable clothes to suit the weather, sensible shoes for periods of standing and walking, and if you are a Girlguiding member, to wear your uniform top. Long hair should be tied back and jewellery removed (wedding bands are permitted). We will provide aprons on the day.

## Food safety and hygiene

We will be following best practice for food safety and hygiene in the tearoom and will ask all volunteers to:

- Wash their hands upon arrival and as necessary throughout the session.
- To use tongs to handle food. We will have separate tongs for our vegan and gluten-free products.
- To help keep the area clean and tidy throughout the day.
- To pass any questions about ingredients, allergens or dietary requirements to the Leader in Charge.
